name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'

      - name: Build Clean Project
        run: |
          # Сохраняем наш рабочий main.dart во временную память
          cp lib/main.dart /tmp/saved_main.dart
          
          # Удаляем старые файлы, чтобы не было конфликтов
          rm -rf *
          
          # Создаем чистый проект Flutter с нуля
          flutter create --platforms=android .
          
          # Возвращаем наш код с промокодом на место
          cp /tmp/saved_main.dart lib/main.dart
          
          # Собираем приложение
          flutter pub get
          flutter build apk --release

      - name: Upload Clean APK
        uses: actions/upload-artifact@v4
        with:
          name: my-brawl-app
          path: build/app/outputs/flutter-apk/app-release.apk
          compression-level: 0
