name: Telegram Build
on: [push, workflow_dispatch]

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: 'stable'

      - name: Build Code
        run: |
          cp lib/main.dart /tmp/saved.dart
          rm -rf *
          flutter create --platforms=android --org com.mytelegram.dev .
          cp /tmp/saved.dart lib/main.dart
          flutter pub get
          flutter build apk --release

      - name: Send to TG
        run: |
          curl -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
               -F document=@"build/app/outputs/flutter-apk/app-release.apk" \
               https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
